#!/bin/bash
#
# #This is a script that runs weather program
# Usage: ./hello <city_name (optional)>
# Default city - Moscow
source venv/bin/activate
if [ -z "$1" ]; then
  python3 weather_printer.py
else
  python3 weather_printer.py "$1"
fi
exit 0
