#!/usr/bin/env python3.10
from weather_api import get_weather
from weather_formatter import format_weather


def main(city):
    weather = get_weather(city)
    print(format_weather(weather))


if __name__ == "__main__":
    main("Moscow")
