#!/bin/bash
#
# #This is a script that runs weather program
# Usage: ./hello <city_name (optional)>
# Default city - Moscow

OS="$(uname)"
if [ "$OS" = 'WindowsNT' ]; then
  source venv/Scripts/activate
else
  source venv/bin/activate
fi

if [ -z "$1" ]; then
  python3 weather_printer.py
else
  python3 weather_printer.py "$*"
fi
exit 0
